### PR TITLE
TIED-60: Upgrade Python to 3.9, upgrade package versions, add DEFAULT_AUTO_FIELD

### PR DESCRIPTION
**Pull request by danipran**
## Description

- Upgrade Python to 3.9.
- Upgrade all the packages as high as possible.
- Add a missing `DEFAULT_AUTO_FIELD` in Django settings and related migrations.

## Related Issue(s)

**[TIED-60](https://helsinkisolutionoffice.atlassian.net/browse/TIED-60)**

## Motivation and Context

Python 3.7's support ends in June 2023, so we want to upgrade it to a fresher version. Some of the packages have already dropped support for 3.7 as well, so this enables us to update them as well.

## How Has This Been Tested?

Locally, running Docker container and the unit tests w/ warnings enabled:
```
PYTHONWARNINGS=always docker compose exec django pytest --capture=no
```

## Additional Notes

The original plan was to upgrade Django to 4.1 as well, but it turns out that [django-helusers](https://github.com/City-of-Helsinki/django-helusers) doesn't support Django >=4, so postponing that...

[TIED-60]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by danipran — COMMENTED** [review]
README needs to be updated

**Comment by voneiden** [comment]
New deprecation warnings for some dependencies @ https://github.com/City-of-Helsinki/helerm/actions/runs/4374218764/jobs/7653368407#step:8:207

> future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

Wanna deal with this now or later?

**Review by voneiden — APPROVED** [review]
Changed files LGTM

**Comment by danipran** [comment]
> New deprecation warnings for some dependencies @ https://github.com/City-of-Helsinki/helerm/actions/runs/4374218764/jobs/7653368407#step:8:207
> 
> > future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at [pypa/pip#8559](https://github.com/pypa/pip/issues/8559)
> 
> Wanna deal with these now or later?

Might as well take a closer look at this, seems like this is something that's [coming sooner than later](https://github.com/pypa/pip/milestone/68) 😅 However, this seems to be out of this PR's scope for the time being, so not resolving this problem in this PR.

**Pull request merged**
