### PR TITLE
Update readme and remove sniffer from ClassificationImporter

### PR DESCRIPTION
**Pull request by voneiden**
It was determined that sniffer is still unreliable and most likely no longer required.

### CODE REVIEW

**Review by danipran — COMMENTED** [review]
These are two very unrelated changes tied together in a single commit. Should probably be in separate commits, so reverting one doesn't affect the other.

The changes look fine otherwise. I'll test the Docker setup step by step in a fresh clone. Manual setup; that, I am not going to do; postgres with WSL is a pain in the ass IIRC.

**Review by danipran — CHANGES_REQUESTED** [review]
Docker setup worked fine. Spotted some issues:

- Some bad English in lines 99 and 101 (`will be located at` -> `is located at`, `ui` -> `UI`)
- Inconsistent URLs and port numbers. I realized that I might've broken convention in an earlier PR with the port number (it's 8080 when using Docker, we usually use 8000), but within the scope of this PR, port should be 8080. Port number can be changed in a separate PR if needed. Use either `localhost` or `127.0.0.1` for the address, either is fine, as long as it's consistent.

**Comment by voneiden** [comment]
Maybe 127.0.0.1, sometimes localhost can bring out fun :tm: with IPv6 ::1

**Review by danipran — APPROVED** [review]
LGTM :+1:

**Pull request merged**
